name: CI-CD project

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.1.5

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da Imagem Docker 
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            dantasdev0/aula-primeira-pipeline01:v${{ github.run_number }}
            dantasdev0/aula-primeira-pipeline01:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.1.5

      - name: Configuração do Contexto do Kubernetes 
        uses: azure/k8s-set-context@v4.0.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG01 }}

      - name: Aplicando os manifests Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            ./k8s/deployment.yaml

          images: |
            dantasdev0/aula-primeira-pipeline01:v${{ github.run_number }}
