name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Iniciando o pipeline..."

      - name: Obtenha o código
        uses: actions/checkout@v3

      - name: Decode Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          cat kubeconfig.yaml  # Apenas para debug (remova em produção)
        shell: bash

      - name: Configuração do Contexto do Kubernetes
        run: |
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl config get-contexts
        shell: bash

      - name: Aplicando os manifests Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            ./k8s/deployment.yaml
            ./k8s/service.yaml
          namespace: default
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
